services:
  shuzikexue-web:
    image: kevinpennfun/shuzikexue-web:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first